# .pre-commit-config.yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0 
    hooks:
      - id: flake8
        name: flake8
        additional_dependencies: [flake8-docstrings, flake8-bugbear]
        language_version: python3.10.12

  - repo: local
    hooks:
      - id: run-phy-tests
        name: Run PHY Tests
        entry: pytest test_phy.py
        language: system
        pass_filenames: false
        stages: [commit]
      - id: run-mac-tests
        name: Run MAC Tests
        entry: pytest test_mac.py
        language: system
        pass_filenames: false
        stages: [commit]
      - id: run-utils-tests
        name: Run Utils Tests
        entry: pytest test_utils.py
        language: system
        pass_filenames: false
        stages: [commit]
