repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/hhatto/autopep8
    rev: v2.3.1
    hooks:
      - id: autopep8
        args: ["--diff", "--aggressive"]
        language_version: python3.10

  - repo: local
    hooks:
      - id: poetry run-phy-tests
        name: Run PHY Tests
        entry: pytest tests/test_phy.py
        language: system
        pass_filenames: false
        stages: [commit]
      # - id: poetry run-mac-tests
      #   name: Run MAC Tests
      #   entry: pytest tests/test_mac.py
      #   language: system
      #   pass_filenames: false
      #   stages: [commit]
      # - id: poetry run-utils-tests
      #   name: Run Utils Tests
      #   entry: pytest tests/test_utils.py
      #   language: system
      #   pass_filenames: false
      #   stages: [commit]
